selected_gpu: '1002:7550-1EAE:8811-0000:03:00.0'
plots_time_period: 60
plots_per_row: 2
gpus:
  '1002:7550-1EAE:8811-0000:03:00.0':
    plots:
    - - !Temperature edge
      - !Temperature junction
      - !Temperature mem
    - - GpuClock
      - GpuTargetClock
      - VramClock
    - - FanRpm
      - FanPwm
    - - PowerAverage
      - PowerCap
